package com.business.dao;

import com.business.dao.sqlProvider.PwpMerchantCouponSqlProvider;
import com.business.entity.PwpMerchantCoupon;
import com.business.entity.PwpMerchantCouponCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpMerchantCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMerchantCouponSqlProvider.class, method="countByExample")
    long countByExample(PwpMerchantCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMerchantCouponSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMerchantCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_merchant_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_merchant_coupon (id, car_num, ",
        "client_id, coupon_money, ",
        "coupon_no, create_time, ",
        "expire_time, merchant_id, ",
        "park_id, park_trade_records_id, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{carNum,jdbcType=VARCHAR}, ",
        "#{clientId,jdbcType=INTEGER}, #{couponMoney,jdbcType=DOUBLE}, ",
        "#{couponNo,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{expireTime,jdbcType=TIMESTAMP}, #{merchantId,jdbcType=INTEGER}, ",
        "#{parkId,jdbcType=INTEGER}, #{parkTradeRecordsId,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PwpMerchantCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMerchantCouponSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMerchantCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMerchantCouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="clientId", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_money", property="couponMoney", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_no", property="couponNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="expire_time", property="expireTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="merchant_id", property="merchantId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_trade_records_id", property="parkTradeRecordsId", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PwpMerchantCoupon> selectByExample(PwpMerchantCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, car_num, client_id, coupon_money, coupon_no, create_time, expire_time, merchant_id, ",
        "park_id, park_trade_records_id, update_time",
        "from pwp_merchant_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="clientId", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_money", property="couponMoney", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_no", property="couponNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="expire_time", property="expireTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="merchant_id", property="merchantId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_trade_records_id", property="parkTradeRecordsId", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PwpMerchantCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantCouponSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMerchantCoupon record, @Param("example") PwpMerchantCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantCouponSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMerchantCoupon record, @Param("example") PwpMerchantCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantCouponSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMerchantCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_coupon
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_merchant_coupon",
        "set car_num = #{carNum,jdbcType=VARCHAR},",
          "client_id = #{clientId,jdbcType=INTEGER},",
          "coupon_money = #{couponMoney,jdbcType=DOUBLE},",
          "coupon_no = #{couponNo,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "expire_time = #{expireTime,jdbcType=TIMESTAMP},",
          "merchant_id = #{merchantId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "park_trade_records_id = #{parkTradeRecordsId,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMerchantCoupon record);
}