package com.business.dao;

import com.business.dao.sqlProvider.PwpMerchantSqlProvider;
import com.business.entity.PwpMerchant;
import com.business.entity.PwpMerchantCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpMerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMerchantSqlProvider.class, method="countByExample")
    long countByExample(PwpMerchantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMerchantSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMerchantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_merchant",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_merchant (id, address, ",
        "billing_account_id, contact, ",
        "coupon_balance, coupon_discount, ",
        "create_time, merchant_name, ",
        "merchant_status, merchant_type, ",
        "mobile, park_id, ",
        "phone, photo_url, ",
        "pos_id, super_account, ",
        "super_password, update_time, ",
        "introduction)",
        "values (#{id,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{billingAccountId,jdbcType=INTEGER}, #{contact,jdbcType=VARCHAR}, ",
        "#{couponBalance,jdbcType=DOUBLE}, #{couponDiscount,jdbcType=DOUBLE}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{merchantName,jdbcType=VARCHAR}, ",
        "#{merchantStatus,jdbcType=SMALLINT}, #{merchantType,jdbcType=SMALLINT}, ",
        "#{mobile,jdbcType=VARCHAR}, #{parkId,jdbcType=INTEGER}, ",
        "#{phone,jdbcType=VARCHAR}, #{photoUrl,jdbcType=VARCHAR}, ",
        "#{posId,jdbcType=VARCHAR}, #{superAccount,jdbcType=VARCHAR}, ",
        "#{superPassword,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{introduction,jdbcType=LONGVARCHAR})"
    })
    int insert(PwpMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMerchantSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMerchantSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.INTEGER),
        @Result(column="contact", property="contact", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_balance", property="couponBalance", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_discount", property="couponDiscount", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="merchant_name", property="merchantName", jdbcType=JdbcType.VARCHAR),
        @Result(column="merchant_status", property="merchantStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="merchant_type", property="merchantType", jdbcType=JdbcType.SMALLINT),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo_url", property="photoUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="pos_id", property="posId", jdbcType=JdbcType.VARCHAR),
        @Result(column="super_account", property="superAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="super_password", property="superPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="introduction", property="introduction", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<PwpMerchant> selectByExampleWithBLOBs(PwpMerchantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMerchantSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.INTEGER),
        @Result(column="contact", property="contact", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_balance", property="couponBalance", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_discount", property="couponDiscount", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="merchant_name", property="merchantName", jdbcType=JdbcType.VARCHAR),
        @Result(column="merchant_status", property="merchantStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="merchant_type", property="merchantType", jdbcType=JdbcType.SMALLINT),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo_url", property="photoUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="pos_id", property="posId", jdbcType=JdbcType.VARCHAR),
        @Result(column="super_account", property="superAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="super_password", property="superPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PwpMerchant> selectByExample(PwpMerchantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, address, billing_account_id, contact, coupon_balance, coupon_discount, create_time, ",
        "merchant_name, merchant_status, merchant_type, mobile, park_id, phone, photo_url, ",
        "pos_id, super_account, super_password, update_time, introduction",
        "from pwp_merchant",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.INTEGER),
        @Result(column="contact", property="contact", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_balance", property="couponBalance", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_discount", property="couponDiscount", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="merchant_name", property="merchantName", jdbcType=JdbcType.VARCHAR),
        @Result(column="merchant_status", property="merchantStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="merchant_type", property="merchantType", jdbcType=JdbcType.SMALLINT),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo_url", property="photoUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="pos_id", property="posId", jdbcType=JdbcType.VARCHAR),
        @Result(column="super_account", property="superAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="super_password", property="superPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="introduction", property="introduction", jdbcType=JdbcType.LONGVARCHAR)
    })
    PwpMerchant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMerchant record, @Param("example") PwpMerchantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") PwpMerchant record, @Param("example") PwpMerchantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMerchant record, @Param("example") PwpMerchantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_merchant",
        "set address = #{address,jdbcType=VARCHAR},",
          "billing_account_id = #{billingAccountId,jdbcType=INTEGER},",
          "contact = #{contact,jdbcType=VARCHAR},",
          "coupon_balance = #{couponBalance,jdbcType=DOUBLE},",
          "coupon_discount = #{couponDiscount,jdbcType=DOUBLE},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "merchant_name = #{merchantName,jdbcType=VARCHAR},",
          "merchant_status = #{merchantStatus,jdbcType=SMALLINT},",
          "merchant_type = #{merchantType,jdbcType=SMALLINT},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "photo_url = #{photoUrl,jdbcType=VARCHAR},",
          "pos_id = #{posId,jdbcType=VARCHAR},",
          "super_account = #{superAccount,jdbcType=VARCHAR},",
          "super_password = #{superPassword,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "introduction = #{introduction,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(PwpMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_merchant",
        "set address = #{address,jdbcType=VARCHAR},",
          "billing_account_id = #{billingAccountId,jdbcType=INTEGER},",
          "contact = #{contact,jdbcType=VARCHAR},",
          "coupon_balance = #{couponBalance,jdbcType=DOUBLE},",
          "coupon_discount = #{couponDiscount,jdbcType=DOUBLE},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "merchant_name = #{merchantName,jdbcType=VARCHAR},",
          "merchant_status = #{merchantStatus,jdbcType=SMALLINT},",
          "merchant_type = #{merchantType,jdbcType=SMALLINT},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "photo_url = #{photoUrl,jdbcType=VARCHAR},",
          "pos_id = #{posId,jdbcType=VARCHAR},",
          "super_account = #{superAccount,jdbcType=VARCHAR},",
          "super_password = #{superPassword,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMerchant record);
}