package com.business.dao;

import com.business.dao.sqlProvider.PwpMerchantRechargeCashSqlProvider;
import com.business.entity.PwpMerchantRechargeCash;
import com.business.entity.PwpMerchantRechargeCashCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpMerchantRechargeCashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMerchantRechargeCashSqlProvider.class, method="countByExample")
    long countByExample(PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMerchantRechargeCashSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_merchant_recharge_cash",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_merchant_recharge_cash (id, coupon_amount, ",
        "coupon_balance, create_time, ",
        "merchant_id, park_id, ",
        "recharge_amount, recharge_no, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{couponAmount,jdbcType=DOUBLE}, ",
        "#{couponBalance,jdbcType=DOUBLE}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{merchantId,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{rechargeAmount,jdbcType=DOUBLE}, #{rechargeNo,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PwpMerchantRechargeCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMerchantRechargeCashSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMerchantRechargeCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMerchantRechargeCashSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_amount", property="couponAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_balance", property="couponBalance", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="merchant_id", property="merchantId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="recharge_amount", property="rechargeAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="recharge_no", property="rechargeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PwpMerchantRechargeCash> selectByExample(PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, coupon_amount, coupon_balance, create_time, merchant_id, park_id, recharge_amount, ",
        "recharge_no, update_time",
        "from pwp_merchant_recharge_cash",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_amount", property="couponAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_balance", property="couponBalance", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="merchant_id", property="merchantId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="recharge_amount", property="rechargeAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="recharge_no", property="rechargeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PwpMerchantRechargeCash selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantRechargeCashSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMerchantRechargeCash record, @Param("example") PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantRechargeCashSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMerchantRechargeCash record, @Param("example") PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMerchantRechargeCashSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMerchantRechargeCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_merchant_recharge_cash",
        "set coupon_amount = #{couponAmount,jdbcType=DOUBLE},",
          "coupon_balance = #{couponBalance,jdbcType=DOUBLE},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "merchant_id = #{merchantId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "recharge_amount = #{rechargeAmount,jdbcType=DOUBLE},",
          "recharge_no = #{rechargeNo,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMerchantRechargeCash record);
}