package com.business.dao;

import com.business.dao.sqlProvider.PwpMemberPCardSqlProvider;
import com.business.entity.PwpMemberPCard;
import com.business.entity.PwpMemberPCardCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpMemberPCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberPCardSqlProvider.class, method="countByExample")
    long countByExample(PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMemberPCardSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_member_p_card",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_member_p_card (id, p_card_code, ",
        "p_card_id, p_card_pwd, ",
        "account, add_sequence, ",
        "address, area_id, ",
        "balance, billing_account_id, ",
        "create_time, credentials_code, ",
        "credentials_type, email, ",
        "member_id, member_p_card_status, ",
        "nick_name, password, ",
        "phone, realname, ",
        "salt, sex, update_time, ",
        "weixin_account)",
        "values (#{id,jdbcType=INTEGER}, #{pCardCode,jdbcType=VARCHAR}, ",
        "#{pCardId,jdbcType=VARCHAR}, #{pCardPwd,jdbcType=VARCHAR}, ",
        "#{account,jdbcType=VARCHAR}, #{addSequence,jdbcType=INTEGER}, ",
        "#{address,jdbcType=VARCHAR}, #{areaId,jdbcType=INTEGER}, ",
        "#{balance,jdbcType=DOUBLE}, #{billingAccountId,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{credentialsCode,jdbcType=VARCHAR}, ",
        "#{credentialsType,jdbcType=SMALLINT}, #{email,jdbcType=VARCHAR}, ",
        "#{memberId,jdbcType=INTEGER}, #{memberPCardStatus,jdbcType=SMALLINT}, ",
        "#{nickName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{realname,jdbcType=VARCHAR}, ",
        "#{salt,jdbcType=VARCHAR}, #{sex,jdbcType=SMALLINT}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{weixinAccount,jdbcType=VARCHAR})"
    })
    int insert(PwpMemberPCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMemberPCardSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMemberPCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberPCardSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="add_sequence", property="addSequence", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DOUBLE),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.SMALLINT),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_p_card_status", property="memberPCardStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.SMALLINT),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="weixin_account", property="weixinAccount", jdbcType=JdbcType.VARCHAR)
    })
    List<PwpMemberPCard> selectByExample(PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, p_card_code, p_card_id, p_card_pwd, account, add_sequence, address, area_id, ",
        "balance, billing_account_id, create_time, credentials_code, credentials_type, ",
        "email, member_id, member_p_card_status, nick_name, password, phone, realname, ",
        "salt, sex, update_time, weixin_account",
        "from pwp_member_p_card",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="add_sequence", property="addSequence", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DOUBLE),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.SMALLINT),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_p_card_status", property="memberPCardStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.SMALLINT),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="weixin_account", property="weixinAccount", jdbcType=JdbcType.VARCHAR)
    })
    PwpMemberPCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberPCardSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMemberPCard record, @Param("example") PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberPCardSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMemberPCard record, @Param("example") PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberPCardSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMemberPCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_member_p_card",
        "set p_card_code = #{pCardCode,jdbcType=VARCHAR},",
          "p_card_id = #{pCardId,jdbcType=VARCHAR},",
          "p_card_pwd = #{pCardPwd,jdbcType=VARCHAR},",
          "account = #{account,jdbcType=VARCHAR},",
          "add_sequence = #{addSequence,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=INTEGER},",
          "balance = #{balance,jdbcType=DOUBLE},",
          "billing_account_id = #{billingAccountId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "credentials_code = #{credentialsCode,jdbcType=VARCHAR},",
          "credentials_type = #{credentialsType,jdbcType=SMALLINT},",
          "email = #{email,jdbcType=VARCHAR},",
          "member_id = #{memberId,jdbcType=INTEGER},",
          "member_p_card_status = #{memberPCardStatus,jdbcType=SMALLINT},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "realname = #{realname,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=SMALLINT},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "weixin_account = #{weixinAccount,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMemberPCard record);
}