package com.business.dao;

import com.business.dao.sqlProvider.PwpMemberSqlProvider;
import com.business.entity.PwpMember;
import com.business.entity.PwpMemberCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberSqlProvider.class, method="countByExample")
    long countByExample(PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMemberSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_member",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_member (member_id, address, ",
        "area_id, cert_pic_back, ",
        "cert_pic_front, create_time, ",
        "credentials_code, credentials_type, ",
        "email, first_p_card_id, ",
        "first_p_card_pwd, member_status, ",
        "password, paypwd, ",
        "phone, picture, ",
        "pwd_safe_level, realname, ",
        "safe_code, salt, ",
        "update_time)",
        "values (#{memberId,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{areaId,jdbcType=INTEGER}, #{certPicBack,jdbcType=VARCHAR}, ",
        "#{certPicFront,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{credentialsCode,jdbcType=VARCHAR}, #{credentialsType,jdbcType=SMALLINT}, ",
        "#{email,jdbcType=VARCHAR}, #{firstPCardId,jdbcType=VARCHAR}, ",
        "#{firstPCardPwd,jdbcType=VARCHAR}, #{memberStatus,jdbcType=SMALLINT}, ",
        "#{password,jdbcType=VARCHAR}, #{paypwd,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{picture,jdbcType=VARCHAR}, ",
        "#{pwdSafeLevel,jdbcType=SMALLINT}, #{realname,jdbcType=VARCHAR}, ",
        "#{safeCode,jdbcType=VARCHAR}, #{salt,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PwpMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMemberSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="cert_pic_back", property="certPicBack", jdbcType=JdbcType.VARCHAR),
        @Result(column="cert_pic_front", property="certPicFront", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.SMALLINT),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_id", property="firstPCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_pwd", property="firstPCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_status", property="memberStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="paypwd", property="paypwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd_safe_level", property="pwdSafeLevel", jdbcType=JdbcType.SMALLINT),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="safe_code", property="safeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PwpMember> selectByExample(PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "member_id, address, area_id, cert_pic_back, cert_pic_front, create_time, credentials_code, ",
        "credentials_type, email, first_p_card_id, first_p_card_pwd, member_status, password, ",
        "paypwd, phone, picture, pwd_safe_level, realname, safe_code, salt, update_time",
        "from pwp_member",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="cert_pic_back", property="certPicBack", jdbcType=JdbcType.VARCHAR),
        @Result(column="cert_pic_front", property="certPicFront", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.SMALLINT),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_id", property="firstPCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_pwd", property="firstPCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_status", property="memberStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="paypwd", property="paypwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd_safe_level", property="pwdSafeLevel", jdbcType=JdbcType.SMALLINT),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="safe_code", property="safeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PwpMember selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMember record, @Param("example") PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMember record, @Param("example") PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_member",
        "set address = #{address,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=INTEGER},",
          "cert_pic_back = #{certPicBack,jdbcType=VARCHAR},",
          "cert_pic_front = #{certPicFront,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "credentials_code = #{credentialsCode,jdbcType=VARCHAR},",
          "credentials_type = #{credentialsType,jdbcType=SMALLINT},",
          "email = #{email,jdbcType=VARCHAR},",
          "first_p_card_id = #{firstPCardId,jdbcType=VARCHAR},",
          "first_p_card_pwd = #{firstPCardPwd,jdbcType=VARCHAR},",
          "member_status = #{memberStatus,jdbcType=SMALLINT},",
          "password = #{password,jdbcType=VARCHAR},",
          "paypwd = #{paypwd,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "picture = #{picture,jdbcType=VARCHAR},",
          "pwd_safe_level = #{pwdSafeLevel,jdbcType=SMALLINT},",
          "realname = #{realname,jdbcType=VARCHAR},",
          "safe_code = #{safeCode,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMember record);
}