package com.business.dao;

import com.business.dao.sqlProvider.PwpMcardRuleSqlProvider;
import com.business.entity.PwpMcardRule;
import com.business.entity.PwpMcardRuleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpMcardRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMcardRuleSqlProvider.class, method="countByExample")
    long countByExample(PwpMcardRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMcardRuleSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMcardRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_mcard_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_mcard_rule (id, create_time, ",
        "day_cost, month_cost, ",
        "park_id, rule_status, ",
        "season_cost, type_name, ",
        "update_time, year_cost)",
        "values (#{id,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{dayCost,jdbcType=DOUBLE}, #{monthCost,jdbcType=DOUBLE}, ",
        "#{parkId,jdbcType=INTEGER}, #{ruleStatus,jdbcType=SMALLINT}, ",
        "#{seasonCost,jdbcType=DOUBLE}, #{typeName,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{yearCost,jdbcType=DOUBLE})"
    })
    int insert(PwpMcardRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMcardRuleSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMcardRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMcardRuleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="day_cost", property="dayCost", jdbcType=JdbcType.DOUBLE),
        @Result(column="month_cost", property="monthCost", jdbcType=JdbcType.DOUBLE),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="rule_status", property="ruleStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="season_cost", property="seasonCost", jdbcType=JdbcType.DOUBLE),
        @Result(column="type_name", property="typeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="year_cost", property="yearCost", jdbcType=JdbcType.DOUBLE)
    })
    List<PwpMcardRule> selectByExample(PwpMcardRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, create_time, day_cost, month_cost, park_id, rule_status, season_cost, type_name, ",
        "update_time, year_cost",
        "from pwp_mcard_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="day_cost", property="dayCost", jdbcType=JdbcType.DOUBLE),
        @Result(column="month_cost", property="monthCost", jdbcType=JdbcType.DOUBLE),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="rule_status", property="ruleStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="season_cost", property="seasonCost", jdbcType=JdbcType.DOUBLE),
        @Result(column="type_name", property="typeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="year_cost", property="yearCost", jdbcType=JdbcType.DOUBLE)
    })
    PwpMcardRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMcardRuleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMcardRule record, @Param("example") PwpMcardRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMcardRuleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMcardRule record, @Param("example") PwpMcardRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMcardRuleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMcardRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_rule
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_mcard_rule",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "day_cost = #{dayCost,jdbcType=DOUBLE},",
          "month_cost = #{monthCost,jdbcType=DOUBLE},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "rule_status = #{ruleStatus,jdbcType=SMALLINT},",
          "season_cost = #{seasonCost,jdbcType=DOUBLE},",
          "type_name = #{typeName,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "year_cost = #{yearCost,jdbcType=DOUBLE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMcardRule record);
}