package com.business.dao;

import com.business.dao.sqlProvider.PwpMcardMemberRechargeSqlProvider;
import com.business.entity.PwpMcardMemberRecharge;
import com.business.entity.PwpMcardMemberRechargeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpMcardMemberRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMcardMemberRechargeSqlProvider.class, method="countByExample")
    long countByExample(PwpMcardMemberRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMcardMemberRechargeSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMcardMemberRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_mcard_member_recharge",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_mcard_member_recharge (id, begin_date, ",
        "car_num, cost, create_time, ",
        "end_date, mcard_member_id, ",
        "mcard_pay_type, member_detail_id, ",
        "need_pay, num, operator, ",
        "park_id, pay_status, ",
        "pay_type_id, recharge_no, ",
        "recharge_type, remark, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{beginDate,jdbcType=DATE}, ",
        "#{carNum,jdbcType=VARCHAR}, #{cost,jdbcType=DOUBLE}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{endDate,jdbcType=DATE}, #{mcardMemberId,jdbcType=INTEGER}, ",
        "#{mcardPayType,jdbcType=SMALLINT}, #{memberDetailId,jdbcType=INTEGER}, ",
        "#{needPay,jdbcType=DOUBLE}, #{num,jdbcType=INTEGER}, #{operator,jdbcType=VARCHAR}, ",
        "#{parkId,jdbcType=INTEGER}, #{payStatus,jdbcType=SMALLINT}, ",
        "#{payTypeId,jdbcType=SMALLINT}, #{rechargeNo,jdbcType=VARCHAR}, ",
        "#{rechargeType,jdbcType=SMALLINT}, #{remark,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PwpMcardMemberRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMcardMemberRechargeSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMcardMemberRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMcardMemberRechargeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_date", property="beginDate", jdbcType=JdbcType.DATE),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="cost", property="cost", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.DATE),
        @Result(column="mcard_member_id", property="mcardMemberId", jdbcType=JdbcType.INTEGER),
        @Result(column="mcard_pay_type", property="mcardPayType", jdbcType=JdbcType.SMALLINT),
        @Result(column="member_detail_id", property="memberDetailId", jdbcType=JdbcType.INTEGER),
        @Result(column="need_pay", property="needPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="operator", property="operator", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_status", property="payStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="pay_type_id", property="payTypeId", jdbcType=JdbcType.SMALLINT),
        @Result(column="recharge_no", property="rechargeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="recharge_type", property="rechargeType", jdbcType=JdbcType.SMALLINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PwpMcardMemberRecharge> selectByExample(PwpMcardMemberRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, begin_date, car_num, cost, create_time, end_date, mcard_member_id, mcard_pay_type, ",
        "member_detail_id, need_pay, num, operator, park_id, pay_status, pay_type_id, ",
        "recharge_no, recharge_type, remark, update_time",
        "from pwp_mcard_member_recharge",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_date", property="beginDate", jdbcType=JdbcType.DATE),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="cost", property="cost", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.DATE),
        @Result(column="mcard_member_id", property="mcardMemberId", jdbcType=JdbcType.INTEGER),
        @Result(column="mcard_pay_type", property="mcardPayType", jdbcType=JdbcType.SMALLINT),
        @Result(column="member_detail_id", property="memberDetailId", jdbcType=JdbcType.INTEGER),
        @Result(column="need_pay", property="needPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="operator", property="operator", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_status", property="payStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="pay_type_id", property="payTypeId", jdbcType=JdbcType.SMALLINT),
        @Result(column="recharge_no", property="rechargeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="recharge_type", property="rechargeType", jdbcType=JdbcType.SMALLINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PwpMcardMemberRecharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMcardMemberRechargeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMcardMemberRecharge record, @Param("example") PwpMcardMemberRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMcardMemberRechargeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMcardMemberRecharge record, @Param("example") PwpMcardMemberRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMcardMemberRechargeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMcardMemberRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_mcard_member_recharge
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_mcard_member_recharge",
        "set begin_date = #{beginDate,jdbcType=DATE},",
          "car_num = #{carNum,jdbcType=VARCHAR},",
          "cost = #{cost,jdbcType=DOUBLE},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "end_date = #{endDate,jdbcType=DATE},",
          "mcard_member_id = #{mcardMemberId,jdbcType=INTEGER},",
          "mcard_pay_type = #{mcardPayType,jdbcType=SMALLINT},",
          "member_detail_id = #{memberDetailId,jdbcType=INTEGER},",
          "need_pay = #{needPay,jdbcType=DOUBLE},",
          "num = #{num,jdbcType=INTEGER},",
          "operator = #{operator,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "pay_status = #{payStatus,jdbcType=SMALLINT},",
          "pay_type_id = #{payTypeId,jdbcType=SMALLINT},",
          "recharge_no = #{rechargeNo,jdbcType=VARCHAR},",
          "recharge_type = #{rechargeType,jdbcType=SMALLINT},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMcardMemberRecharge record);
}