package com.business.dao;

import com.business.dao.sqlProvider.PwpParkPortSqlProvider;
import com.business.entity.PwpParkPort;
import com.business.entity.PwpParkPortCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PwpParkPortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpParkPortSqlProvider.class, method="countByExample")
    long countByExample(PwpParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpParkPortSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_park_port",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_park_port (id, local_port_id, ",
        "park_id, port_name, ",
        "port_status)",
        "values (#{id,jdbcType=INTEGER}, #{localPortId,jdbcType=INTEGER}, ",
        "#{parkId,jdbcType=INTEGER}, #{portName,jdbcType=VARCHAR}, ",
        "#{portStatus,jdbcType=SMALLINT})"
    })
    int insert(PwpParkPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpParkPortSqlProvider.class, method="insertSelective")
    int insertSelective(PwpParkPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpParkPortSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="local_port_id", property="localPortId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="port_name", property="portName", jdbcType=JdbcType.VARCHAR),
        @Result(column="port_status", property="portStatus", jdbcType=JdbcType.SMALLINT)
    })
    List<PwpParkPort> selectByExample(PwpParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, local_port_id, park_id, port_name, port_status",
        "from pwp_park_port",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="local_port_id", property="localPortId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="port_name", property="portName", jdbcType=JdbcType.VARCHAR),
        @Result(column="port_status", property="portStatus", jdbcType=JdbcType.SMALLINT)
    })
    PwpParkPort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpParkPortSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpParkPort record, @Param("example") PwpParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpParkPortSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpParkPort record, @Param("example") PwpParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpParkPortSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpParkPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park_port
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_park_port",
        "set local_port_id = #{localPortId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "port_name = #{portName,jdbcType=VARCHAR},",
          "port_status = #{portStatus,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpParkPort record);
}