package com.business.dao;

import com.business.dao.sqlProvider.TParkPortSqlProvider;
import com.business.entity.TParkPort;
import com.business.entity.TParkPortCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TParkPortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @SelectProvider(type=TParkPortSqlProvider.class, method="countByExample")
    long countByExample(TParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TParkPortSqlProvider.class, method="deleteByExample")
    int deleteByExample(TParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_park_port",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_park_port (id, park_id, ",
        "port_id, port_name, ",
        "port_type, computer_index)",
        "values (#{id,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{portId,jdbcType=INTEGER}, #{portName,jdbcType=VARCHAR}, ",
        "#{portType,jdbcType=INTEGER}, #{computerIndex,jdbcType=VARCHAR})"
    })
    int insert(TParkPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @InsertProvider(type=TParkPortSqlProvider.class, method="insertSelective")
    int insertSelective(TParkPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @SelectProvider(type=TParkPortSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="port_id", property="portId", jdbcType=JdbcType.INTEGER),
        @Result(column="port_name", property="portName", jdbcType=JdbcType.VARCHAR),
        @Result(column="port_type", property="portType", jdbcType=JdbcType.INTEGER),
        @Result(column="computer_index", property="computerIndex", jdbcType=JdbcType.VARCHAR)
    })
    List<TParkPort> selectByExample(TParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_id, port_id, port_name, port_type, computer_index",
        "from t_park_port",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="port_id", property="portId", jdbcType=JdbcType.INTEGER),
        @Result(column="port_name", property="portName", jdbcType=JdbcType.VARCHAR),
        @Result(column="port_type", property="portType", jdbcType=JdbcType.INTEGER),
        @Result(column="computer_index", property="computerIndex", jdbcType=JdbcType.VARCHAR)
    })
    TParkPort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TParkPortSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TParkPort record, @Param("example") TParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TParkPortSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TParkPort record, @Param("example") TParkPortCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TParkPortSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TParkPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port
     *
     * @mbg.generated
     */
    @Update({
        "update t_park_port",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "port_id = #{portId,jdbcType=INTEGER},",
          "port_name = #{portName,jdbcType=VARCHAR},",
          "port_type = #{portType,jdbcType=INTEGER},",
          "computer_index = #{computerIndex,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TParkPort record);
}