package com.business.dao;

import com.business.dao.sqlProvider.TPayMentSqlProvider;
import com.business.entity.TPayMent;
import com.business.entity.TPayMentCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TPayMentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @SelectProvider(type=TPayMentSqlProvider.class, method="countByExample")
    long countByExample(TPayMentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TPayMentSqlProvider.class, method="deleteByExample")
    int deleteByExample(TPayMentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_pay_ment",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_pay_ment (id, park_id, ",
        "pay_type, is_start_hump, ",
        "is_holiday, is_low_peak)",
        "values (#{id,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{payType,jdbcType=INTEGER}, #{isStartHump,jdbcType=INTEGER}, ",
        "#{isHoliday,jdbcType=INTEGER}, #{isLowPeak,jdbcType=INTEGER})"
    })
    int insert(TPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @InsertProvider(type=TPayMentSqlProvider.class, method="insertSelective")
    int insertSelective(TPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @SelectProvider(type=TPayMentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_type", property="payType", jdbcType=JdbcType.INTEGER),
        @Result(column="is_start_hump", property="isStartHump", jdbcType=JdbcType.INTEGER),
        @Result(column="is_holiday", property="isHoliday", jdbcType=JdbcType.INTEGER),
        @Result(column="is_low_peak", property="isLowPeak", jdbcType=JdbcType.INTEGER)
    })
    List<TPayMent> selectByExample(TPayMentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_id, pay_type, is_start_hump, is_holiday, is_low_peak",
        "from t_pay_ment",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_type", property="payType", jdbcType=JdbcType.INTEGER),
        @Result(column="is_start_hump", property="isStartHump", jdbcType=JdbcType.INTEGER),
        @Result(column="is_holiday", property="isHoliday", jdbcType=JdbcType.INTEGER),
        @Result(column="is_low_peak", property="isLowPeak", jdbcType=JdbcType.INTEGER)
    })
    TPayMent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPayMentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TPayMent record, @Param("example") TPayMentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPayMentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TPayMent record, @Param("example") TPayMentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPayMentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TPayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_ment
     *
     * @mbg.generated
     */
    @Update({
        "update t_pay_ment",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "pay_type = #{payType,jdbcType=INTEGER},",
          "is_start_hump = #{isStartHump,jdbcType=INTEGER},",
          "is_holiday = #{isHoliday,jdbcType=INTEGER},",
          "is_low_peak = #{isLowPeak,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPayMent record);
}