server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #测试服务器
    url: jdbc:mysql://rm-wz9d21p5za0w2ja2xo.mysql.rds.aliyuncs.com:3306/eparking?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8
    username: eparking
    password: 20peraikgn14@
  http:
    multipart-maxFileSize: 10MB
    multipart-maxRequestSize: 10MB


  #本机
  #    url: jdbc:mysql://localhost:3306/eparking?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8
  #    username: root
  #    password: 123456

  freemarker:
    request-context-attribute: req  #req访问request
  　suffix: .ftl  #后缀名
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql

logging:
  level:
    com:
      business:
        dao: debug
thread:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10
redis:
  host: localhost
  port: 6379
  password: root
  jedis:
    pool:
      max-idle:  -1
      min-idle: 0
      max-active:  -1
      max-wait: -1
  timeout: 0


