package com.business.entity;

public class TChargeRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.is_Holiday_Use
     *
     * @mbg.generated
     */
    private Integer isHolidayUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.timesec_start
     *
     * @mbg.generated
     */
    private String timesecStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.timesec_end
     *
     * @mbg.generated
     */
    private String timesecEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.car_type_id
     *
     * @mbg.generated
     */
    private Integer carTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.free_time
     *
     * @mbg.generated
     */
    private Integer freeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.free_time_fee
     *
     * @mbg.generated
     */
    private Double freeTimeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.base_time1
     *
     * @mbg.generated
     */
    private Integer baseTime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.base_time1_fee
     *
     * @mbg.generated
     */
    private Double baseTime1Fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.base_time2
     *
     * @mbg.generated
     */
    private Integer baseTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.base_time2_fee
     *
     * @mbg.generated
     */
    private Double baseTime2Fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.unit_time
     *
     * @mbg.generated
     */
    private Integer unitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.unit_time_fee
     *
     * @mbg.generated
     */
    private Double unitTimeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.h24_unit_time
     *
     * @mbg.generated
     */
    private Integer h24UnitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.h24_unit_time_fee
     *
     * @mbg.generated
     */
    private Double h24UnitTimeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.surpass_time
     *
     * @mbg.generated
     */
    private Integer surpassTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.max_day1_fee
     *
     * @mbg.generated
     */
    private Double maxDay1Fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.max_dayn_fee
     *
     * @mbg.generated
     */
    private Double maxDaynFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.h24_rule
     *
     * @mbg.generated
     */
    private Integer h24Rule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.max_sectime_fee
     *
     * @mbg.generated
     */
    private Double maxSectimeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.is_max_sectime_fee_by_add
     *
     * @mbg.generated
     */
    private Integer isMaxSectimeFeeByAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge_rule.is_max_24_fee_by_add
     *
     * @mbg.generated
     */
    private Integer isMax24FeeByAdd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.id
     *
     * @return the value of t_charge_rule.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.id
     *
     * @param id the value for t_charge_rule.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.park_id
     *
     * @return the value of t_charge_rule.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.park_id
     *
     * @param parkId the value for t_charge_rule.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.is_Holiday_Use
     *
     * @return the value of t_charge_rule.is_Holiday_Use
     *
     * @mbg.generated
     */
    public Integer getIsHolidayUse() {
        return isHolidayUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.is_Holiday_Use
     *
     * @param isHolidayUse the value for t_charge_rule.is_Holiday_Use
     *
     * @mbg.generated
     */
    public void setIsHolidayUse(Integer isHolidayUse) {
        this.isHolidayUse = isHolidayUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.timesec_start
     *
     * @return the value of t_charge_rule.timesec_start
     *
     * @mbg.generated
     */
    public String getTimesecStart() {
        return timesecStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.timesec_start
     *
     * @param timesecStart the value for t_charge_rule.timesec_start
     *
     * @mbg.generated
     */
    public void setTimesecStart(String timesecStart) {
        this.timesecStart = timesecStart == null ? null : timesecStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.timesec_end
     *
     * @return the value of t_charge_rule.timesec_end
     *
     * @mbg.generated
     */
    public String getTimesecEnd() {
        return timesecEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.timesec_end
     *
     * @param timesecEnd the value for t_charge_rule.timesec_end
     *
     * @mbg.generated
     */
    public void setTimesecEnd(String timesecEnd) {
        this.timesecEnd = timesecEnd == null ? null : timesecEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.car_type_id
     *
     * @return the value of t_charge_rule.car_type_id
     *
     * @mbg.generated
     */
    public Integer getCarTypeId() {
        return carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.car_type_id
     *
     * @param carTypeId the value for t_charge_rule.car_type_id
     *
     * @mbg.generated
     */
    public void setCarTypeId(Integer carTypeId) {
        this.carTypeId = carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.free_time
     *
     * @return the value of t_charge_rule.free_time
     *
     * @mbg.generated
     */
    public Integer getFreeTime() {
        return freeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.free_time
     *
     * @param freeTime the value for t_charge_rule.free_time
     *
     * @mbg.generated
     */
    public void setFreeTime(Integer freeTime) {
        this.freeTime = freeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.free_time_fee
     *
     * @return the value of t_charge_rule.free_time_fee
     *
     * @mbg.generated
     */
    public Double getFreeTimeFee() {
        return freeTimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.free_time_fee
     *
     * @param freeTimeFee the value for t_charge_rule.free_time_fee
     *
     * @mbg.generated
     */
    public void setFreeTimeFee(Double freeTimeFee) {
        this.freeTimeFee = freeTimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.base_time1
     *
     * @return the value of t_charge_rule.base_time1
     *
     * @mbg.generated
     */
    public Integer getBaseTime1() {
        return baseTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.base_time1
     *
     * @param baseTime1 the value for t_charge_rule.base_time1
     *
     * @mbg.generated
     */
    public void setBaseTime1(Integer baseTime1) {
        this.baseTime1 = baseTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.base_time1_fee
     *
     * @return the value of t_charge_rule.base_time1_fee
     *
     * @mbg.generated
     */
    public Double getBaseTime1Fee() {
        return baseTime1Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.base_time1_fee
     *
     * @param baseTime1Fee the value for t_charge_rule.base_time1_fee
     *
     * @mbg.generated
     */
    public void setBaseTime1Fee(Double baseTime1Fee) {
        this.baseTime1Fee = baseTime1Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.base_time2
     *
     * @return the value of t_charge_rule.base_time2
     *
     * @mbg.generated
     */
    public Integer getBaseTime2() {
        return baseTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.base_time2
     *
     * @param baseTime2 the value for t_charge_rule.base_time2
     *
     * @mbg.generated
     */
    public void setBaseTime2(Integer baseTime2) {
        this.baseTime2 = baseTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.base_time2_fee
     *
     * @return the value of t_charge_rule.base_time2_fee
     *
     * @mbg.generated
     */
    public Double getBaseTime2Fee() {
        return baseTime2Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.base_time2_fee
     *
     * @param baseTime2Fee the value for t_charge_rule.base_time2_fee
     *
     * @mbg.generated
     */
    public void setBaseTime2Fee(Double baseTime2Fee) {
        this.baseTime2Fee = baseTime2Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.unit_time
     *
     * @return the value of t_charge_rule.unit_time
     *
     * @mbg.generated
     */
    public Integer getUnitTime() {
        return unitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.unit_time
     *
     * @param unitTime the value for t_charge_rule.unit_time
     *
     * @mbg.generated
     */
    public void setUnitTime(Integer unitTime) {
        this.unitTime = unitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.unit_time_fee
     *
     * @return the value of t_charge_rule.unit_time_fee
     *
     * @mbg.generated
     */
    public Double getUnitTimeFee() {
        return unitTimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.unit_time_fee
     *
     * @param unitTimeFee the value for t_charge_rule.unit_time_fee
     *
     * @mbg.generated
     */
    public void setUnitTimeFee(Double unitTimeFee) {
        this.unitTimeFee = unitTimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.h24_unit_time
     *
     * @return the value of t_charge_rule.h24_unit_time
     *
     * @mbg.generated
     */
    public Integer getH24UnitTime() {
        return h24UnitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.h24_unit_time
     *
     * @param h24UnitTime the value for t_charge_rule.h24_unit_time
     *
     * @mbg.generated
     */
    public void setH24UnitTime(Integer h24UnitTime) {
        this.h24UnitTime = h24UnitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.h24_unit_time_fee
     *
     * @return the value of t_charge_rule.h24_unit_time_fee
     *
     * @mbg.generated
     */
    public Double getH24UnitTimeFee() {
        return h24UnitTimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.h24_unit_time_fee
     *
     * @param h24UnitTimeFee the value for t_charge_rule.h24_unit_time_fee
     *
     * @mbg.generated
     */
    public void setH24UnitTimeFee(Double h24UnitTimeFee) {
        this.h24UnitTimeFee = h24UnitTimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.surpass_time
     *
     * @return the value of t_charge_rule.surpass_time
     *
     * @mbg.generated
     */
    public Integer getSurpassTime() {
        return surpassTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.surpass_time
     *
     * @param surpassTime the value for t_charge_rule.surpass_time
     *
     * @mbg.generated
     */
    public void setSurpassTime(Integer surpassTime) {
        this.surpassTime = surpassTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.max_day1_fee
     *
     * @return the value of t_charge_rule.max_day1_fee
     *
     * @mbg.generated
     */
    public Double getMaxDay1Fee() {
        return maxDay1Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.max_day1_fee
     *
     * @param maxDay1Fee the value for t_charge_rule.max_day1_fee
     *
     * @mbg.generated
     */
    public void setMaxDay1Fee(Double maxDay1Fee) {
        this.maxDay1Fee = maxDay1Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.max_dayn_fee
     *
     * @return the value of t_charge_rule.max_dayn_fee
     *
     * @mbg.generated
     */
    public Double getMaxDaynFee() {
        return maxDaynFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.max_dayn_fee
     *
     * @param maxDaynFee the value for t_charge_rule.max_dayn_fee
     *
     * @mbg.generated
     */
    public void setMaxDaynFee(Double maxDaynFee) {
        this.maxDaynFee = maxDaynFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.h24_rule
     *
     * @return the value of t_charge_rule.h24_rule
     *
     * @mbg.generated
     */
    public Integer getH24Rule() {
        return h24Rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.h24_rule
     *
     * @param h24Rule the value for t_charge_rule.h24_rule
     *
     * @mbg.generated
     */
    public void setH24Rule(Integer h24Rule) {
        this.h24Rule = h24Rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.max_sectime_fee
     *
     * @return the value of t_charge_rule.max_sectime_fee
     *
     * @mbg.generated
     */
    public Double getMaxSectimeFee() {
        return maxSectimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.max_sectime_fee
     *
     * @param maxSectimeFee the value for t_charge_rule.max_sectime_fee
     *
     * @mbg.generated
     */
    public void setMaxSectimeFee(Double maxSectimeFee) {
        this.maxSectimeFee = maxSectimeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.is_max_sectime_fee_by_add
     *
     * @return the value of t_charge_rule.is_max_sectime_fee_by_add
     *
     * @mbg.generated
     */
    public Integer getIsMaxSectimeFeeByAdd() {
        return isMaxSectimeFeeByAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.is_max_sectime_fee_by_add
     *
     * @param isMaxSectimeFeeByAdd the value for t_charge_rule.is_max_sectime_fee_by_add
     *
     * @mbg.generated
     */
    public void setIsMaxSectimeFeeByAdd(Integer isMaxSectimeFeeByAdd) {
        this.isMaxSectimeFeeByAdd = isMaxSectimeFeeByAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge_rule.is_max_24_fee_by_add
     *
     * @return the value of t_charge_rule.is_max_24_fee_by_add
     *
     * @mbg.generated
     */
    public Integer getIsMax24FeeByAdd() {
        return isMax24FeeByAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge_rule.is_max_24_fee_by_add
     *
     * @param isMax24FeeByAdd the value for t_charge_rule.is_max_24_fee_by_add
     *
     * @mbg.generated
     */
    public void setIsMax24FeeByAdd(Integer isMax24FeeByAdd) {
        this.isMax24FeeByAdd = isMax24FeeByAdd;
    }
}